[package]
name = "azvpn"
version = "0.1.0"
description = "Cross-platform Azure VPN client"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "azvpn"
path = "src/main.rs"

[dependencies]
azvpn-auth = { workspace = true }
azvpn-core = { workspace = true }
azvpn-openvpn = { workspace = true }
azvpn-profile = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true }
hickory-resolver = { workspace = true }
reqwest = { workspace = true }
libc = { workspace = true }
net-route = { workspace = true }
open = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
azvpn-tunnel-darwin = { workspace = true }

[lints]
workspace = true
