[package]
name = "azvpn-profile"
version = "0.1.0"
description = "Azure VPN profile XML parsing"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
quick-xml = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
